export const products = [
    {
      id: 1,
      title: 'Zapatos Deportivos',
      description: 'Zapatos cómodos para correr y caminar.',
      price: 120,
      image: 'https://example.com/shoes.jpg',
    },
    {
      id: 2,
      title: 'Camisa Casual',
      description: 'Camisa perfecta para ocasiones informales.',
      price: 45,
      image: 'https://example.com/shirt.jpg',
    },
    {
      id: 3,
      title: 'Pantalones Jeans',
      description: 'Pantalones de mezclilla para uso diario.',
      price: 60,
      image: 'https://example.com/jeans.jpg',
    },
    {
      id: 4,
      title: 'Gorra de Béisbol',
      description: 'Protege tu cabeza del sol con estilo.',
      price: 20,
      image: 'https://example.com/hat.jpg',
    },
    {
      id: 5,
      title: 'Chaqueta de Cuero',
      description: 'Chaqueta elegante para clima frío.',
      price: 150,
      image: 'https://example.com/leather-jacket.jpg',
    },
    {
      id: 6,
      title: 'Bolso de Mano',
      description: 'Bolso elegante para cualquier ocasión.',
      price: 70,
      image: 'https://example.com/bag.jpg',
    },
    {
      id: 7,
      title: 'Reloj Deportivo',
      description: 'Reloj resistente para deportes y aventuras.',
      price: 200,
      image: 'https://example.com/watch.jpg',
    },
    {
      id: 8,
      title: 'Gafas de Sol',
      description: 'Protege tuso.',
      price: 50,
      image: 'https://example.com/sunglasses.jpg',
    },
    {
      id: 9,
      title: 'Bufanda de Invierno',
      description: 'Bufanda cálida.',
      price: 25,
      image: 'https://example.com/scarf.jpg',
    },
    {
      id: 10,
      title: 'Camisa de Manga Larga',
      description: 'Camisa cómoda .',
      price: 30,
      image: 'https://example.com/long-sleeve.jpg',
    },
    {
      id: 11,
      title: 'Camisa de Manga Larga',
      description: 'Camisa cómoda .',
      price: 30,
      image: 'https://example.com/long-sleeve.jpg',
    },
    {
      id: 12,
      title: 'Camisa de Manga Larga',
      description: 'Camisa cómoda .',
      price: 30,
      image: 'https://example.com/long-sleeve.jpg',
    },
    {
      id: 13,
      title: 'Camisa de Manga Larga',
      description: 'Camisa cómoda .',
      price: 30,
      image: 'https://example.com/long-sleeve.jpg',
    },
    {
      id: 14,
      title: 'Camisa de Manga Larga',
      description: 'Camisa cómoda .',
      price: 30,
      image: 'https://example.com/long-sleeve.jpg',
    },
    {
      id: 15,
      title: 'Camisa de Manga Larga',
      description: 'Camisa cómoda .',
      price: 30,
      image: 'https://example.com/long-sleeve.jpg',
    },
    {
      id: 16,
      title: 'Camisa de Manga Larga',
      description: 'Camisa cómoda .',
      price: 30,
      image: 'https://example.com/long-sleeve.jpg',
    },
    {
      id: 17,
      title: 'Camisa de Manga Larga',
      description: 'Camisa cómoda .',
      price: 30,
      image: 'https://example.com/long-sleeve.jpg',
    },
    {
      id: 18,
      title: 'Camisa de Manga Larga',
      description: 'Camisa cómoda .',
      price: 30,
      image: 'https://example.com/long-sleeve.jpg',
    },
    {
      id: 19,
      title: 'Camisa de Manga Larga',
      description: 'Camisa cómoda .',
      price: 30,
      image: 'https://example.com/long-sleeve.jpg',
    },
    {
      id: 20,
      title: 'Camisa de Manga Larga',
      description: 'Camisa cómoda .',
      price: 30,
      image: 'https://example.com/long-sleeve.jpg',
    },
    {
      id: 21,
      title: 'Camisa de Manga Larga',
      description: 'Camisa cómoda .',
      price: 30,
      image: 'https://example.com/long-sleeve.jpg',
    },
    {
      id: 22,
      title: 'Camisa de Manga Larga',
      description: 'Camisa cómoda .',
      price: 30,
      image: 'https://example.com/long-sleeve.jpg',
    },
    {
      id: 23,
      title: 'Camisa de Manga Larga',
      description: 'Camisa cómoda .',
      price: 30,
      image: 'https://example.com/long-sleeve.jpg',
    },
    {
      id: 24,
      title: 'Camisa de Manga Larga',
      description: 'Camisa cómoda .',
      price: 30,
      image: 'https://example.com/long-sleeve.jpg',
    },
    {
      id: 25,
      title: 'Camisa de Manga Larga',
      description: 'Camisa cómoda .',
      price: 30,
      image: 'https://example.com/long-sleeve.jpg',
    },
    {
      id: 26,
      title: 'Camisa de Manga Larga',
      description: 'Camisa cómoda .',
      price: 30,
      image: 'https://example.com/long-sleeve.jpg',
    },
    {
      id: 27,
      title: 'Camisa de Manga Larga',
      description: 'Camisa cómoda .',
      price: 30,
      image: 'https://example.com/long-sleeve.jpg',
    },
    {
      id: 28,
      title: 'Camisa de Manga Larga',
      description: 'Camisa cómoda .',
      price: 30,
      image: 'https://example.com/long-sleeve.jpg',
    },
    {
      id: 29,
      title: 'Camisa de Manga Larga',
      description: 'Camisa cómoda .',
      price: 30,
      image: 'https://example.com/long-sleeve.jpg',
    },
    {
      id: 30,
      title: 'Camisa de Manga Larga',
      description: 'Camisa cómoda .',
      price: 30,
      image: 'https://example.com/long-sleeve.jpg',
    },
    {
      id: 31,
      title: 'Camisa de Manga Larga',
      description: 'Camisa cómoda .',
      price: 30,
      image: 'https://example.com/long-sleeve.jpg',
    },
    {
      id: 32,
      title: 'Camisa de Manga Larga',
      description: 'Camisa cómoda .',
      price: 30,
      image: 'https://example.com/long-sleeve.jpg',
    },
    {
      id: 33,
      title: 'Camisa de Manga Larga',
      description: 'Camisa cómoda .',
      price: 30,
      image: 'https://example.com/long-sleeve.jpg',
    },
    {
      id: 34,
      title: 'Camisa de Manga Larga',
      description: 'Camisa cómoda .',
      price: 30,
      image: 'https://example.com/long-sleeve.jpg',
    },
    {
      id: 35,
      title: 'Camisa de Manga Larga',
      description: 'Camisa cómoda .',
      price: 30,
      image: 'https://example.com/long-sleeve.jpg',
    },
    {
      id: 36,
      title: 'Camisa de Manga Larga',
      description: 'Camisa cómoda .',
      price: 30,
      image: 'https://example.com/long-sleeve.jpg',
    },
    {
      id: 38,
      title: 'Camisa de Manga Larga',
      description: 'Camisa cómoda .',
      price: 30,
      image: 'https://example.com/long-sleeve.jpg',
    },

    // Productos adicionales para completar hasta el número 50
    ];
  